// Automatically generated by scripts/extract-blog-metadata.mjs
export interface SimplifiedBlogPost {
  id: string;
  title: string;
  desc: string;
  excerpt: string;
  date: string;
  author: string;
  image: string;
  category: 'Fiyat' | 'Rehber' | 'Yasal' | 'Teknik' | 'Bölge';
  readingTime: number;
}

export const blogMetadata: Record<string, SimplifiedBlogPost> = {
  "eskisehir-nakliyat-fiyatlari": {
    "id": "eskisehir-nakliyat-fiyatlari",
    "title": "Eskişehir Evden Eve Nakliyat Fiyatları Nasıl Belirlenir?",
    "desc": "Eskişehir'de ev taşıma maliyetlerini etkileyen oda sayısı, kat yükseklikleri ve asansör gereksinimlerini detaylıca inceliyoruz.",
    "excerpt": "Ev taşıma maliyetlerini etkileyen oda sayısı, kat durumları, asansör kurulumu ve yol mesafesi gibi temel parametreleri inceliyoruz.",
    "date": "2026-08-01",
    "author": "Tanzer Pınar",
    "image": "/img/esen-slayt-1.jpg",
    "category": "Fiyat",
    "readingTime": 6
  },
  "esya-paketleme-rehberi": {
    "id": "esya-paketleme-rehberi",
    "title": "Taşınma Öncesi Pratik Eşya Paketleme Yöntemleri",
    "desc": "Kırılacak mutfak gereçleri, cam eşyalar ve mobilyaların taşınırken zarar görmemesi için kullanılan ambalajlama standartları ve pratik paketleme rehberi.",
    "excerpt": "Kırılacak cam eşyalar ve mobilyaların zarar görmemesi için kullanılan çift kat balonlu naylon ve Kraft kutu paketleme teknikleri.",
    "date": "2026-07-28",
    "author": "Marangoz Mehmet Usta",
    "image": "/img/paketleme-detay-v3.jpg",
    "category": "Rehber",
    "readingTime": 1
  },
  "asansorlu-tasima-avantajlari": {
    "id": "asansorlu-tasima-avantajlari",
    "title": "Yüksek Katlı Binalarda Mobil Asansörlü Nakliyat Avantajları",
    "desc": "Tepebaşı ve Odunpazarı bölgelerindeki yüksek katlı rezidanslarda dış cephe teleskopik mobil asansör sistemlerinin sağladığı eşya hasarsızlık avantajları.",
    "excerpt": "Tepebaşı ve Odunpazarı gibi apartman yoğunluğu yüksek bölgelerde dış cephe eşya asansörlerinin hasarı önleme ve zaman tasarrufu faydaları.",
    "date": "2026-07-15",
    "author": "Operatör Caner Usta",
    "image": "/img/esen-slayt-2.jpg",
    "category": "Teknik",
    "readingTime": 1
  },
  "eskisehir-tasinma-maliyeti-2026": {
    "id": "eskisehir-tasinma-maliyeti-2026",
    "title": "Eskişehir Taşınma Maliyeti 2026: Fiyatlar & Masraflar",
    "desc": "Eskişehir evden eve nakliyat fiyatları 2026 maliyet rehberi. Tepebaşı ve Odunpazarı taşınma giderleri, asansör kiralama ve gizli nakliye masrafları dökümü.",
    "excerpt": "2026 yılı Eskişehir evden eve nakliyat fiyatları, gizli masraflar, asansör kurulum maliyetleri ve taşınma bütçesi hazırlama rehberi.",
    "date": "2026-08-21",
    "author": "Esen 26 Lojistik Editör",
    "image": "/img/esen-slayt-1.jpg",
    "category": "Fiyat",
    "readingTime": 6
  },
  "nakliyat-sigortasi-nedir": {
    "id": "nakliyat-sigortasi-nedir",
    "title": "Nakliyat Sigortası Nedir, Neleri Kapsamaz?",
    "desc": "Evden eve nakliyat sigortası rehberi. Taşınma sigortası poliçe okuma adımları, emtia taşıma sigortası kapsamı ve nelerin garanti dışı kaldığı.",
    "excerpt": "Ev taşırken eşyalarınızı güvenceye alan nakliyat sigortasının türleri, kapsam dışı kalan durumlar ve poliçe doğrulama yöntemleri.",
    "date": "2026-03-05",
    "author": "Tesisat ve Güvence Uzmanı",
    "image": "/img/esen-slayt-2.jpg",
    "category": "Yasal",
    "readingTime": 6
  },
  "k3-yetki-belgesi-nedir": {
    "id": "k3-yetki-belgesi-nedir",
    "title": "K3 Yetki Belgesi Nedir, Nasıl Sorgulanır?",
    "desc": "K3 yetki belgesi nedir, nasıl sorgulanır? Ev ve ofis taşımacılığında zorunlu olan Ulaştırma Bakanlığı K3 belgesi sorgulama adımları ve cezai yaptırımlar.",
    "excerpt": "Evden eve nakliyat firmalarında bulunması zorunlu olan K3 yetki belgesinin önemi, sorgulama aşamaları ve korsan firmaların riskleri.",
    "date": "2026-04-18",
    "author": "Yasal Uyum ve Lojistik Müdürü",
    "image": "/img/esen-slayt-3.jpg",
    "category": "Yasal",
    "readingTime": 6
  },
  "tasinmadan-30-gun-once-hazirlik": {
    "id": "tasinmadan-30-gun-once-hazirlik",
    "title": "Taşınmadan 30 Gün Önce Başlayan Hazırlık Takvimi",
    "desc": "Taşınma hazırlığı takvimi. Ev taşımadan 30 gün önce yapılması gereken abonelik iptalleri, koli hazırlığı, nakliye firması seçimi ve taşınma günü planı.",
    "excerpt": "Taşınma gününü stressiz atlatmak için 4 hafta öncesinden başlayan, gün gün detaylandırılmış ev taşıma hazırlık rehberi.",
    "date": "2026-05-12",
    "author": "Esen 26 Nakliyat Operasyon Koordinatörü",
    "image": "/img/paketleme-detay-v3.jpg",
    "category": "Rehber",
    "readingTime": 6
  },
  "asansorlu-nakliyat-mi-merdivenle-mi": {
    "id": "asansorlu-nakliyat-mi-merdivenle-mi",
    "title": "Asansörlü Nakliyat mı Merdiven mi? Karşılaştırma",
    "desc": "Asansörlü nakliyat ile merdivenle taşıma karşılaştırması. Eskişehir'de taşınırken maliyet, süre, güvenlik ve bina içi eşya hasarı karşılaştırma analizi.",
    "excerpt": "Ev taşırken modüler dış cephe asansörü kullanmak ile insan gücüyle merdivenden taşımanın maliyet, zaman ve hasar açısından detaylı karşılaştırması.",
    "date": "2026-06-02",
    "author": "Esen 26 Nakliyat Baş Operatörü",
    "image": "/img/esen-slayt-2.jpg",
    "category": "Teknik",
    "readingTime": 6
  },
  "beyaz-esya-tasima-rehberi": {
    "id": "beyaz-esya-tasima-rehberi",
    "title": "Beyaz Eşya Taşıma Rehberi & Dinlendirme Süresi",
    "desc": "Buzdolabı, çamaşır makinesi ve televizyon taşıma rehberi. Taşınma sonrası buzdolabının fişini takmadan önce neden 4 saat beklenmelidir?",
    "excerpt": "Hassas beyaz eşyaların taşınma öncesi hazırlıkları, tambur kilidi kullanımı, paketleme detayları ve taşınma sonrası kompresör dinlendirme süresi.",
    "date": "2026-06-25",
    "author": "Teknik Destek ve Kurulum Şefi",
    "image": "/img/paketleme-detay-v3.jpg",
    "category": "Teknik",
    "readingTime": 6
  },
  "tasinirken-yapilan-yasal-hatalar": {
    "id": "tasinirken-yapilan-yasal-hatalar",
    "title": "Kiracıdan Ev Sahibine: Taşınırken Yapılan 8 Yasal Hata",
    "desc": "Kiracı ve ev sahiplerinin taşınma sürecinde yaptığı yasal hatalar. Kira sözleşmesi feshi, depozito iadesi, ikametgah bildirimi ve yasal haklar.",
    "excerpt": "Kira sözleşmesinin feshinden depozito iadesine, resmi adres bildirim sürelerinden apartman yönetim yasalarına kadar taşınmanın hukuki boyutları.",
    "date": "2026-07-01",
    "author": "Hukuk Müşaviri Av. Selim Can",
    "image": "/img/esen-slayt-3.jpg",
    "category": "Yasal",
    "readingTime": 6
  },
  "sehirlerarasi-tasimada-esya-hasari": {
    "id": "sehirlerarasi-tasimada-esya-hasari",
    "title": "Şehirlerarası Taşımada Eşya Hasar Görürse Ne Yapılır?",
    "desc": "Şehirlerarası ev taşımada eşya hasarı durumunda yapılması gerekenler. Hasar tespit tutanağı hazırlama, sigorta talep adımları ve yasal haklar.",
    "excerpt": "Uzun yol taşımacılığında kırılan, çizilen veya kaybolan eşyalar için hukuki süreç, hasar tutanağı yazımı ve sigorta şirketi başvuru rehberi.",
    "date": "2026-07-20",
    "author": "Esen 26 Nakliyat Hasar Destek Masası",
    "image": "/img/esen-slayt-1.jpg",
    "category": "Rehber",
    "readingTime": 6
  },
  "ofis-tasima-plani": {
    "id": "ofis-tasima-plani",
    "title": "Ofis Taşıma Planı: İş Kaybı Yaşamadan Hafta Sonu Taşınma",
    "desc": "Eskişehir kurumsal ofis ve işyeri taşıma planı rehberi. İş kaybı yaşamadan, hafta sonu kesintisiz ofis taşımacılığı adımları ve etiketli kutulama teknikleri.",
    "excerpt": "Kurumsal firmaların iş kaybı ve zaman zararı yaşamadan, cuma akşamından pazartesi sabahına kadar tamamlanan ofis nakliyesi planlama adımları.",
    "date": "2026-07-02",
    "author": "Kurumsal Lojistik Danışmanı",
    "image": "/img/esen-slayt-3.jpg",
    "category": "Rehber",
    "readingTime": 6
  },
  "eskisehir-semt-rehberi": {
    "id": "eskisehir-semt-rehberi",
    "title": "Eskişehir Semt Rehberi: Hangi Semtte Oturmalı?",
    "desc": "Eskişehir semt rehberi. Taşınma öncesinde Odunpazarı, Tepebaşı ve Sivrihisar ilçelerinin mahalleleri, ulaşım olanakları ve yaşam standartları karşılaştırması.",
    "excerpt": "Eskişehir'de konut arayanlar için Odunpazarı, Tepebaşı ve Sivrihisar semtlerinin yaşam kalitesi, konut yapıları ve sosyal imkanlar karşılaştırma analizi.",
    "date": "2026-07-10",
    "author": "Eskişehir Kent Gözlemcisi",
    "image": "/img/esen-slayt-1.jpg",
    "category": "Bölge",
    "readingTime": 6
  },
  "kapora-tuzagi-ucuz-nakliyat": {
    "id": "kapora-tuzagi-ucuz-nakliyat",
    "title": "Kapora Tuzağı: Ucuz Nakliye Teklifleri Analizi",
    "desc": "Ucuz nakliyat firmalarının kapora tuzağı ve taşınma günü dolandırıcılığı rehberi. Güvenli nakliyat sözleşmesi ve doğru fiyat analizi.",
    "excerpt": "İnternet reklamlarında maliyetin çok altında fiyat verip kapora aldıktan sonra taşınma günü ek ücret isteyen korsan firmaların çalışma yöntemleri.",
    "date": "2026-07-28",
    "author": "Lojistik Denetim ve Güvenlik Sorumlusu",
    "image": "/img/esen-slayt-2.jpg",
    "category": "Fiyat",
    "readingTime": 6
  },
  "eskisehirda-tasinmak-icin-en-uygun-zaman": {
    "id": "eskisehirda-tasinmak-icin-en-uygun-zaman",
    "title": "Eskişehir'de Taşınmak İçin En Uygun Zaman Hangisi?",
    "desc": "Eskişehir'de taşınmak için en uygun zaman analizi. Yaz sıcakları, okul dönemleri, hafta içi/hafta sonu fiyat farkları ve taşınma tarihi seçimi tüyoları.",
    "excerpt": "Eskişehir'in aşırı yaz sıcaklarından kaçınmak, okulların açılış dönemleri ve hafta içi taşınma avantajlarıyla bütçe dostu nakliyat tarihi belirleme rehberi.",
    "date": "2026-08-05",
    "author": "Esen 26 Nakliyat Planlama Müdürü",
    "image": "/img/esen-slayt-1.jpg",
    "category": "Rehber",
    "readingTime": 5
  }
};
