/**
 * IMAGE BLUR PLACEHOLDERS FOR NEXT/IMAGE
 * Automatically generated by scripts/optimize-images.mjs
 */

export const IMAGE_BLURS: Record<string, string> = {
  "asansor-kurulum": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARcVf4salw7ALEAAA/taujXs3M22+w9bfvyVnVBmM1BM/6H89Fkt8Jlq6wM7GOQpI5/cmbTgx0CAAAA==",
  "marangozluk-v3": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJYwCw7B/2iOkYTQuhesAA/tS2lvFaVQXWUCOpc6zkfoMqMVv2iSja+4+3mzycCM3Otpd6IJqbmFsgR9JQdxkujSYG4o9hqrLYAAAA",
  "paketleme-detay-v3": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZgCdABtAESyjhkM4AP7ICOMHmSNA7lv4qTgjcIBCfl0qr520Qiw9wUnh+4MHYIv+/1gvRWd1PPim9rx/5EAqUXYAzeADDlQKwA6MAFfa4AAA",
  "esen-slayt-1": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJYwAAWYK3HzNJXdPnGAAA/sXfIXuP/w5h6+yLe4w/nD4ZSPojET/Ff/b8pQkQNSeoD+CUedHjEZitX/V78zhvWV1wQJpwpJBkM0BoSKv3/5V87O0TStCgAAA=",
  "esen-slayt-2": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJQBYdgxo73oYHv0BiYlwAAPyBo+PKMVAhgWvGIbjccPlEBL3AXDm6TsWk6fholxeENgcrlHoITE65zeT2uk6iWrAF3J4sARed9G4yegAAAA==",
  "esen-slayt-3": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJQBOgAyWXI/sVQx9YvcAA/tO07WLQD9jL7veMLZVzSQ5en/ox9luevVagOig6Wt0MXnJQ+gyUDY2jQcrdEKK7ch416A6NjIxl0FAA"
};
